### ISSUE TITLE
uniapp 怎么运行到 手机模拟器 

### ISSUE THREAD

**Issue by alaric8** [uappkit/uapp#11]

**Comment by zencodex** [comment]
问题有点模糊，什么系统环境，大概参照如下：

方法一：可以编译自定义基座打包 (uapp run build:dev)，然后通过 hbx 运行到手机功能。注意iOS模拟器不支持自定义基座。

方法二：通过离线工程，android 用 android studio 调试运行到模拟器。iOS 使用 xcode 调试运行到模拟器。这个方法需要每次运行前使用 uapp run prepare 把 webapp 资源更新下。这个方法不适合频繁调试 webapp。

如果仅仅是 webapp，没有第三方模块的情况下，也可以先使用官方的基座调试。

**Comment by alaric8** [comment]
Thank  you very much for your dedication
