### ISSUE TITLE
如何更新到最新的uniRuntime?

### ISSUE THREAD

**Issue by bestK** [uappkit/uapp#13]
之前我按照这个文章配置了， hbx 插件包，版本为3.98
https://zhuanlan.zhihu.com/p/666909815

现在想要升级到最新的`4.24`,请问是不是将windows上的 `E:\HBuilderX\plugins` ,上传到linux `/usr/local/hbuilderx-linux/plugins`,然后再更新`~/uappsdk/android/SDK` 为最新的离线打包sdk就行了

![image](https://github.com/user-attachments/assets/d41bea03-5c2a-489e-91a0-60788e2739bd)

**Comment by zencodex** [comment]
可以参照我做的linux SDK的目录，这些插件一般够用，如果还有其他的，再添加下：

```
├── about
├── compile-dart-sass
├── compile-less
├── compile-node-sass
├── uniapp-cli
└── uniapp-cli-vite
```

将最新版本上传到linux 里后，然后进去每个执行一下 npm install ，把里面的包都升级下。有些包是包含系统 native 库的，不能copy就完事。所以不同系统，要单独更新下。

如果更新完，也可以给大家分享一份哦。

也可以禁止SDK 版本不一致的提示，修改 manifest.json ，在“app-plus”->"compatible" 节点下添加配置：

```
"app-plus": {  
    "compatible": {  
        "ignoreVersion": true //true表示忽略版本检查提示框，HBuilderX1.9.0及以上版本支持  
    },  
//....  
}, 
```

**Comment by bestK** [comment]
谢谢您

**Comment by bestK** [comment]
## 我测试成功了，简单说下步骤
_如图更新到了4.24_
![image](https://github.com/user-attachments/assets/92ce218e-8b77-4953-9952-6a62b154958c)

1. 到 https://nativesupport.dcloud.net.cn/AppDocs/download/android 下载最新的离线打包SDK
2. Windows 更新自己想要的 HbuilderX 版本
3. 复制更新的版本 HbuilderX/plugins/uniapp-cli 到 /usr/local/hbuilderx-linux/plugins

---
我设想的一些功能，如果有时间的话我可以试着加上

## Feature
- [ ] uapp cli 支持自定义 sdk/plugins 数据源 
- [ ] uapp cli 支持使用 uapp android sdk list 查看数据源提供的sdk版本，并展示本机安装状态
- [ ] uapp cli 支持使用 uapp android sdk install <sdk_version> 安装指定版本的sdk
- [ ] uapp cli  支持使用 uapp android sdk set <sdk_version> 指定构建过程中的版本
