### ISSUE TITLE
vue3 脚手架创建的项目 运行提示index.html不存在

### ISSUE THREAD

**Issue by White-lmp** [uappkit/uapp#14]
![1](https://github.com/user-attachments/assets/a0717226-d4e5-460b-917e-fe60f2739152)
查看源码应该是这个变量设置错误，导致走到了hbuilder 打包而不是脚手架的打包

**Comment by zencodex** [comment]
最新版的命令和 uniapp-cli 保持一致，很可能你的命令和vue版本对应的有问题。
比如 vue2 编译app的命令: `uapp run build:app-plus`
vue3 编译 app 的命令: `uapp run build:app`

保证命令和平台，vue2版对应好，如果再有问题，可以再反馈。

**Comment by White-lmp** [comment]
依然不行，vue用的是3.5.11
![ddddd](https://github.com/user-attachments/assets/fca38975-2470-4f81-aaac-ea29133a3728)

**Comment by zencodex** [comment]
> 依然不行，vue用的是3.5.11 ![ddddd](https://private-user-images.githubusercontent.com/62785499/389464024-fca38975-2470-4f81-aaac-ea29133a3728.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjI2NzgsIm5iZiI6MTczMjYyMjM3OCwicGF0aCI6Ii82Mjc4NTQ5OS8zODk0NjQwMjQtZmNhMzg5NzUtMjQ3MC00ZjgxLWFhYWMtZWEyOTEzM2EzNzI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDExNTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxN2Q0Njc5ZWRiYjRiZTkwODllOTFhM2UwODlmODkzMWUxYWM1YTIzMGRiZjc3MDRlZjEwMDRiZmNmNmRiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uHI-axOvT4757MfKf-9xLSitgoubvc2vyKm3HWAUj3k)

应该是模版有问题，uniapp-cli 和 hbx 创建工程有区别。
你用hbx编译看看，应该也一样吧。使用 hbx 创建一个空工程，然后对比一下，我见过这个问题，但不记得哪里差异引起的。

**Comment by White-lmp** [comment]
正常使用 hbx 创建工程是不会出现这问题的

**Comment by zencodex** [comment]
<img width="759" alt="image" src="https://github.com/user-attachments/assets/7a4a10bb-c39d-45c1-b84e-9a5c67ad64b4">


上面是我的测试，hbx创建工程，`uapp run build:h5` 没有问题。

如果无法解决，可以提供下复现问题的工程代码

**Comment by White-lmp** [comment]
https://github.com/White-lmp/demo-uapp-uniapp-vue3-demo

hbx我这边也是没问题的，是cli创建的才会出现此问题
