### ISSUE TITLE
我在尝试使用此工具目前遇到问题

### ISSUE THREAD

**Issue by simple890921** [uappkit/uapp#2]
通过npm 或者 仓库下载的后 。

- 但我不知道如何正确使用它
- 通过文档配置且下载了默认安卓工程(通过各种骚操作尝试)，可以正常打包了。

--------
##### 遇到问题如下：
问题1：
使用命令如下：`uapp manifest sync xxxxxxx`

```
build.gradle 中没有 manifestPlaceholders->DCLOUD_APPKEY 等属性
但是在custom.gradle找到了它 我将它手动复制过来了。
```
- 且我在 [安卓离线工程下发现了历史版本](https://github.com/uappkit/uapp-android/commit/bf2a8706607bff70ef47fce8507d7831dcac4712)，如有必要请大佬维护下相关版本

问题2：
uapp中 cli.js文件,自由项目工程编译目录定死了
```
src/unpackage/resources

是否可以 让用户自定义或者通过命令行参数指定。
```

**Comment by zencodex** [comment]
你好，

问题1：

> custom.gradle 的确是后加的，这个文件是在 build.gradle 中 include 的，这个文件的作用就是放一些自定义的参数，所以不需要再往 build.gradle 里面去移动。 这样做的好处，不需要频繁维护 build.gradle，只需要根据自身情况 custom.gradle 里修改参数或增加其他参数配置即可。


问题2：

这个是考虑到都是官方目前仅支持 HBuilderx 调试，这个编译目录通常也是 `src/unpackage/resources`，你这边修改目录的需求是什么呢

**Comment by simple890921** [comment]
> Reference in ne

1：这是不是就意味着我在维护离线打包工程的时候 将离线打包key之类的手动copy过去就可以了。

2：

我使用的是npx degit xxxxxx 新建的项目。

编译后到了项目中的根目录 ， `dist/resources/xxx` 

例如：``npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`

我目前的解决办法是修改cli.js，我也尝试了修改打包的环境变量 `UNI_OUTPUT_DIR`似乎没有效果

**Comment by zencodex** [comment]
新提交了一个 v2.1.8 版本，可以支持自定义 prepare 命令 COPY的目录。

还增加了pepare 前后的自定义脚本，可以实现：
1. pepare 执行前 先build
2. prepare 执行后，用 `uapp publish debug` 生成离线包。

换其他脚本也可以，不过不需要就不要设置，一般都是 HBuilder X打包，是要和 appid 绑定的，自行 npm 生成的前提也是必须要先有 DCloud 分配的 appid。

自定配置在 manifest.json => uapp 节点下，${SRC} 为manifest.json 的同级目录

```
"uapp": {
  "prepare.dir": "${SRC}/../dist/build/app",
  "prepare.before": "cd ${SRC}/../ && npm run build:app",
  "prepare.after": "uapp publish debug"
},
```

**Comment by simple890921** [comment]
感谢🙏
