### ISSUE TITLE
想问下有没有不借助HbuilderX 去调试app的方式

### ISSUE THREAD

**Issue by ysneo** [uappkit/uapp#4]
自己弄了离线打包可以不借助hbuilder, 但是感觉开发调试app脱离Hbuilder没有想到方法；不知道你怎么看？

**Comment by zencodex** [comment]
严重赞成你的建议，我提过这个问题，但这个问题貌似影响dcloud官方对hbx 的把控，不爱理睬：

<https://ask.dcloud.net.cn/question/156266>

**Comment by ysneo** [comment]
他们推的就是HBuilderX 算是命根子了， 估计不会有cli的后续命令；

后没有调试的方案😂， 目前想的就是启动android studio的模拟器，但是怎么把dev的资源安装进去

**Comment by zencodex** [comment]
这个就没研究过了，理论上知道存放手机端的存放位置，是可以自己同步过去。有兴趣可以加微信 yinqisen 一起研究
