### ISSUE TITLE
有没有Linux下开发uniapp的相关文档？

### ISSUE THREAD

**Issue by scmiot** [uappkit/uapp#7]
看了这篇：
https://zhuanlan.zhihu.com/p/666909815
配置后，可以在Lubuntu 23.10下运行，文章中的SDK包是3.95的，官方现在3.98,尝试按照现有目录升级失败，提示：
“HBuilderX 需要安装插件 => uni-app (vue2) 编译器”，
如果有linux下配置或移植的详细文档那就好了，谢谢！

**Comment by zencodex** [comment]
最新 HBuilder 3.98 Linux 平台插件包已更新到：

<https://artisansoft.feishu.cn/docx/NZRHdetSzoi8VEx7KcYcuivpnqd>

**Comment by YumeMichi** [comment]
> 最新 HBuilder 3.98 Linux 平台插件包已更新到：
> 
> https://artisansoft.feishu.cn/docx/NZRHdetSzoi8VEx7KcYcuivpnqd

你好，能否支持一下vue3？目前这个我试了一下包括hbuilderx和uapp new创建的vue3都无法编译。
```
当前使用 manifest: XXXXX/demo2/manifest.json
当前工程类型为 webapp
Compiler version: 3.98（vue3）
Compiling...
failed to load config from XXXXX/demo2/vite.config.js
Build failed with errors.
```
