### ISSUE TITLE
请问支持wgt热更新包构建吗

### ISSUE THREAD

**Issue by fgy888** [uappkit/uapp#8]

**Comment by zencodex** [comment]
wgt 就是 zip 压缩包：
> .wgt: Zip archive data, at least v1.0 to extract, compression method=store

所以在 build 完成后，再zip压缩，改名为 xxx.wgt 即可。

**Comment by zencodex** [comment]
@fgy888  可以参考下这位朋友分享的，正好里面有 wgt 生成的代码

#9

**Comment by fgy888** [comment]
> @fgy888 可以参考下这位朋友分享的，正好里面有 wgt 生成的代码
> 
> #9

谢谢
